---
- import_playbook: ../init/evaluate_groups.yml

- name: Ensure there are nodes to provision
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - fail:
      msg: >
        Detected no new nodes in inventory. Please add hosts to the
        either new_infranodes or new_appnodes host groups to add nodes.
    when:
    - g_new_infranode_hosts | default([]) | length == 0
    - g_new_appnode_hosts | default([]) | length == 0
  - fail:
      msg: >
        Please run playbooks/openshift-master/scaleup.yml if you need to
        scale up both masters and nodes.  This playbook is only needed if
        you are only adding new nodes and not new masters.
    when:
    - g_new_infranode_hosts | default([]) | length > 0
    - g_new_appnode_hosts | default([]) | length > 0
    - g_new_master_hosts | default([]) | length > 0

# if g_new_node_hosts is not empty, oo_nodes_to_config will be set to
# g_new_node_hosts via evaluate_groups.yml

- import_playbook: ../prerequisites.yml
  vars:
    l_scale_up_hosts: "oo_infranodes_to_config:oo_appnodes_to_config"
    l_base_packages_hosts: "oo_infranodes_to_config:oo_appnodes_to_config"
    l_init_fact_hosts: "oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config:oo_infranodes_to_config:oo_appnodes_to_config"
    l_sanity_check_hosts: "{{ groups['oo_infranodes_to_config'] | union(groups['oo_masters_to_config']) | union(groups['oo_appnodes_to_config'])}}"

- import_playbook: ../init/version.yml
  vars:
    l_openshift_version_set_hosts: "oo_infranodes_to_config:oo_appnodes_to_config:!oo_first_master"
    l_openshift_version_check_hosts: "oo_infranodes_to_config:oo_appnodes_to_config"

- import_playbook: private/config.yml
